name: build my angular app

on: 
 push: 
   branches: [ main ]

jobs:
  build-angular-app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.0
    - name: setup node JS
      uses: actions/setup-node@v6.4.0
      with:
        node-version: 22.x
    - name: install dependencies
      run: npm install
    - name: build angular app
      run: npm run build
    
     
      
     
      
     
      
    
    

  
   
